### ISSUE TITLE
Random exporter behavior

### ISSUE THREAD

**Issue by tangrammer** [akvo/akvo-lumen#2591]
# Context
Behavior is not regular

# Problem or idea
What is the cause?

# Solution or next step
How could we solve it?

**Comment by iperdomo** [comment]
Current backend-service definition for `lumen-blue-green-gateway`
````
affinityCookieTtlSec: 0
backends:
- balancingMode: RATE
  capacityScaler: 1.0
  group: https://www.googleapis.com/compute/v1/projects/akvo-lumen/zones/europe-west1-d/instanceGroups/k8s-ig--81169246e8cac04d
  maxRatePerInstance: 1.0
connectionDraining:
  drainingTimeoutSec: 0
creationTimestamp: '2018-02-05T09:20:15.572-08:00'
description: '{"kubernetes.io/service-name":"default/lumen-blue-green-gateway","kubernetes.io/service-port":"80"}'
enableCDN: false
fingerprint: YKH4gE80MLE=
healthChecks:
- https://www.googleapis.com/compute/v1/projects/akvo-lumen/global/healthChecks/k8s-be-32404--81169246e8cac04d
id: '5257033482836978848'
kind: compute#backendService
loadBalancingScheme: EXTERNAL
logConfig:
  enable: true
  sampleRate: 1.0
name: k8s-be-32404--81169246e8cac04d
port: 32404
portName: port32404
protocol: HTTP
selfLink: https://www.googleapis.com/compute/v1/projects/akvo-lumen/global/backendServices/k8s-be-32404--81169246e8cac04d
sessionAffinity: NONE
timeoutSec: 100
````
